let timeLeft = 7200; // 2 hours in seconds
const questions = [
    {
    id: 1,
    question: "Which gland is known as the 'master gland' of the endocrine system?",
    options: ["Pituitary gland", "Thyroid gland", "Adrenal gland", "Pancreas"],
    answer: "Pituitary gland",
  },
  {
    id: 2,
    question: "What hormone does the pancreas produce to regulate blood sugar?",
    options: ["Insulin", "Adrenaline", "Thyroxine", "Cortisol"],
    answer: "Insulin",
  },
  {
    id: 3,
    question: "Which hormone is responsible for the fight-or-flight response?",
    options: ["Adrenaline", "Growth hormone", "Insulin", "Estrogen"],
    answer: "Adrenaline",
  },
  {
    id: 4,
    question: "Which gland regulates metabolism through the secretion of thyroxine?",
    options: ["Thyroid gland", "Pituitary gland", "Adrenal gland", "Parathyroid gland"],
    answer: "Thyroid gland",
  },
  {
    id: 5,
    question: "What hormone controls the body's calcium levels?",
    options: ["Parathyroid hormone", "Insulin", "Cortisol", "Melatonin"],
    answer: "Parathyroid hormone",
  },
  {
    id: 6,
    question: "Which hormone stimulates milk production in mammals?",
    options: ["Prolactin", "Oxytocin", "Estrogen", "Testosterone"],
    answer: "Prolactin",
  },
  {
    id: 7,
    question: "Which gland produces melatonin, regulating the sleep-wake cycle?",
    options: ["Pineal gland", "Pituitary gland", "Thyroid gland", "Adrenal gland"],
    answer: "Pineal gland",
  },
  {
    id: 8,
    question: "Which hormone increases blood sugar by stimulating glucose release from the liver?",
    options: ["Glucagon", "Insulin", "Aldosterone", "Growth hormone"],
    answer: "Glucagon",
  },
  {
    id: 9,
    question: "Which part of the adrenal gland produces cortisol?",
    options: ["Adrenal cortex", "Adrenal medulla", "Pituitary gland", "Thyroid gland"],
    answer: "Adrenal cortex",
  },
  {
    id: 10,
    question: "Which hormone regulates water balance in the body by acting on the kidneys?",
    options: ["Antidiuretic hormone (ADH)", "Oxytocin", "Insulin", "Thyroxine"],
    answer: "Antidiuretic hormone (ADH)",
  },
  {
    id: 11,
    question: "Which hormone is secreted by the ovaries?",
    options: ["Estrogen", "Testosterone", "Cortisol", "Adrenaline"],
    answer: "Estrogen",
  },
  {
    id: 12,
    question: "Which hormone triggers uterine contractions during childbirth?",
    options: ["Oxytocin", "Prolactin", "Adrenaline", "Growth hormone"],
    answer: "Oxytocin",
  },
  {
    id: 13,
    question: "Which hormone regulates metabolism and growth by stimulating protein synthesis?",
    options: ["Growth hormone", "Insulin", "Glucagon", "Thyroxine"],
    answer: "Growth hormone",
  },
  {
    id: 14,
    question: "Which gland is located above the kidneys?",
    options: ["Adrenal gland", "Pituitary gland", "Thyroid gland", "Parathyroid gland"],
    answer: "Adrenal gland",
  },
  {
    id: 15,
    question: "Which hormone lowers blood calcium levels?",
    options: ["Calcitonin", "Parathyroid hormone", "Insulin", "Cortisol"],
    answer: "Calcitonin",
  },
  {
    id: 16,
    question: "Which hormone is responsible for male secondary sexual characteristics?",
    options: ["Testosterone", "Estrogen", "Progesterone", "Prolactin"],
    answer: "Testosterone",
  },
  {
    id: 17,
    question: "Which gland produces thyroid-stimulating hormone (TSH)?",
    options: ["Pituitary gland", "Thyroid gland", "Adrenal gland", "Pancreas"],
    answer: "Pituitary gland",
  },
  {
    id: 18,
    question: "Which hormone controls the fight-or-flight response by increasing heart rate?",
    options: ["Adrenaline", "Cortisol", "Insulin", "Growth hormone"],
    answer: "Adrenaline",
  },
  {
    id: 19,
    question: "Which hormone stimulates the release of eggs from the ovary?",
    options: ["Luteinizing hormone (LH)", "Follicle-stimulating hormone (FSH)", "Prolactin", "Estrogen"],
    answer: "Luteinizing hormone (LH)",
  },
  {
    id: 20,
    question: "Which hormone regulates the menstrual cycle?",
    options: ["Estrogen", "Testosterone", "Adrenaline", "Oxytocin"],
    answer: "Estrogen",
  },
  {
    id: 21,
    question: "Which hormone secreted by the pancreas lowers blood glucose levels?",
    options: ["Insulin", "Glucagon", "Cortisol", "Aldosterone"],
    answer: "Insulin",
  },
  {
    id: 22,
    question: "Which hormone helps regulate sodium and potassium levels in the blood?",
    options: ["Aldosterone", "Cortisol", "Adrenaline", "Growth hormone"],
    answer: "Aldosterone",
  },
  {
    id: 23,
    question: "Which hormone promotes development of female secondary sexual characteristics?",
    options: ["Estrogen", "Testosterone", "Progesterone", "Oxytocin"],
    answer: "Estrogen",
  },
  {
    id: 24,
    question: "Which gland secretes hormones that regulate metabolism, growth, and development?",
    options: ["Thyroid gland", "Pituitary gland", "Adrenal gland", "Pancreas"],
    answer: "Thyroid gland",
  },
  {
    id: 25,
    question: "Which hormone prepares the uterus for pregnancy?",
    options: ["Progesterone", "Estrogen", "Oxytocin", "Prolactin"],
    answer: "Progesterone",
  },
  {
    id: 26,
    question: "Which hormone stimulates the thyroid gland to produce thyroid hormones?",
    options: ["Thyroid-stimulating hormone (TSH)", "Growth hormone", "Adrenocorticotropic hormone (ACTH)", "Insulin"],
    answer: "Thyroid-stimulating hormone (TSH)",
  },
  {
    id: 27,
    question: "What hormone is released by the adrenal medulla?",
    options: ["Adrenaline and noradrenaline", "Cortisol", "Aldosterone", "Insulin"],
    answer: "Adrenaline and noradrenaline",
  },
  {
    id: 28,
    question: "Which hormone increases the reabsorption of sodium and water in the kidneys?",
    options: ["Aldosterone", "ADH", "Cortisol", "Glucagon"],
    answer: "Aldosterone",
  },
  {
    id: 29,
    question: "Which hormone secreted by the pancreas raises blood glucose levels?",
    options: ["Glucagon", "Insulin", "Somatostatin", "Thyroxine"],
    answer: "Glucagon",
  },
  {
    id: 30,
    question: "Which hormone regulates the circadian rhythm?",
    options: ["Melatonin", "Cortisol", "Thyroxine", "Growth hormone"],
    answer: "Melatonin",
  },
  {
    id: 31,
    question: "Which hormone inhibits the release of growth hormone?",
    options: ["Somatostatin", "Thyroxine", "Insulin", "Adrenaline"],
    answer: "Somatostatin",
  },
  {
    id: 32,
    question: "Which hormone stimulates the production of red blood cells?",
    options: ["Erythropoietin", "Insulin", "Cortisol", "Growth hormone"],
    answer: "Erythropoietin",
  },
  {
    id: 33,
    question: "Which hormone is secreted by the thymus gland?",
    options: ["Thymosin", "Adrenaline", "Thyroxine", "Insulin"],
    answer: "Thymosin",
  },
  {
    id: 34,
    question: "Which hormone promotes protein synthesis and growth in muscles?",
    options: ["Growth hormone", "Glucagon", "Cortisol", "Insulin"],
    answer: "Growth hormone",
  },
  {
    id: 35,
    question: "Which hormone released by the adrenal cortex helps the body respond to stress?",
    options: ["Cortisol", "Aldosterone", "Adrenaline", "Insulin"],
    answer: "Cortisol",
  },
  {
    id: 36,
    question: "Which hormone regulates electrolyte balance and blood pressure?",
    options: ["Aldosterone", "ADH", "Thyroxine", "Growth hormone"],
    answer: "Aldosterone",
  },
  {
    id: 37,
    question: "Which hormone promotes development of female reproductive organs?",
    options: ["Estrogen", "Testosterone", "Progesterone", "Oxytocin"],
    answer: "Estrogen",
  },
  {
    id: 38,
    question: "Which hormone triggers ovulation?",
    options: ["Luteinizing hormone (LH)", "Follicle-stimulating hormone (FSH)", "Prolactin", "Estrogen"],
    answer: "Luteinizing hormone (LH)",
  },
  {
    id: 39,
    question: "Which hormone stimulates sperm production in males?",
    options: ["Follicle-stimulating hormone (FSH)", "Luteinizing hormone (LH)", "Testosterone", "Estrogen"],
    answer: "Follicle-stimulating hormone (FSH)",
  },
  {
    id: 40,
    question: "Which hormone regulates metabolism by controlling the rate of energy use?",
    options: ["Thyroxine", "Growth hormone", "Cortisol", "Adrenaline"],
    answer: "Thyroxine",
  },
  {
    id: 41,
    question: "Which hormone controls the release of cortisol from the adrenal gland?",
    options: ["Adrenocorticotropic hormone (ACTH)", "Growth hormone", "Thyroid-stimulating hormone (TSH)", "Insulin"],
    answer: "Adrenocorticotropic hormone (ACTH)",
  },
  {
    id: 42,
    question: "Which hormone regulates blood sugar by lowering glucose levels?",
    options: ["Insulin", "Glucagon", "Cortisol", "Adrenaline"],
    answer: "Insulin",
  },
  {
    id: 43,
    question: "Which hormone is responsible for milk ejection during breastfeeding?",
    options: ["Oxytocin", "Prolactin", "Estrogen", "Testosterone"],
    answer: "Oxytocin",
  },
  {
    id: 44,
    question: "Which hormone controls calcium absorption in the intestines?",
    options: ["Calcitriol (active vitamin D)", "Parathyroid hormone", "Calcitonin", "Insulin"],
    answer: "Calcitriol (active vitamin D)",
  },
  {
    id: 45,
    question: "Which hormone is secreted by the anterior pituitary to stimulate the adrenal cortex?",
    options: ["Adrenocorticotropic hormone (ACTH)", "Growth hormone", "Thyroid-stimulating hormone (TSH)", "Prolactin"],
    answer: "Adrenocorticotropic hormone (ACTH)",
  },
  {
    id: 46,
    question: "Which hormone regulates water retention in the kidneys?",
    options: ["Antidiuretic hormone (ADH)", "Aldosterone", "Cortisol", "Thyroxine"],
    answer: "Antidiuretic hormone (ADH)",
  },
  {
    id: 47,
    question: "Which gland is responsible for regulating metabolism, growth, and development?",
    options: ["Thyroid gland", "Pituitary gland", "Adrenal gland", "Pancreas"],
    answer: "Thyroid gland",
  },
  {
    id: 48,
    question: "Which hormone prepares the uterus for implantation of the fertilized egg?",
    options: ["Progesterone", "Estrogen", "Oxytocin", "Testosterone"],
    answer: "Progesterone",
  },
  {
    id: 49,
    question: "Which hormone stimulates the development of male secondary sexual characteristics?",
    options: ["Testosterone", "Estrogen", "Progesterone", "Cortisol"],
    answer: "Testosterone",
  },
  {
    id: 50,
    question: "Which hormone is responsible for regulating the body's response to stress?",
    options: ["Cortisol", "Adrenaline", "Insulin", "Growth hormone"],
    answer: "Cortisol",
  },
  {
    id: 51,
    question: "Which hormone is secreted by the anterior pituitary and stimulates thyroid hormone production?",
    options: ["Thyroid-stimulating hormone (TSH)", "Adrenocorticotropic hormone (ACTH)", "Growth hormone", "Prolactin"],
    answer: "Thyroid-stimulating hormone (TSH)",
  },
  {
    id: 52,
    question: "Which hormone decreases blood calcium levels by promoting calcium deposition in bones?",
    options: ["Calcitonin", "Parathyroid hormone", "Calcitriol", "Insulin"],
    answer: "Calcitonin",
  },
  {
    id: 53,
    question: "What hormone produced by the pancreas inhibits the secretion of insulin and glucagon?",
    options: ["Somatostatin", "Glucagon", "Insulin", "Pancreatic polypeptide"],
    answer: "Somatostatin",
  },
  {
    id: 54,
    question: "Which hormone secreted by the adrenal cortex helps regulate metabolism and immune response?",
    options: ["Cortisol", "Aldosterone", "Adrenaline", "Insulin"],
    answer: "Cortisol",
  },
  {
    id: 55,
    question: "Which hormone is responsible for stimulating the release of milk from the mammary glands?",
    options: ["Oxytocin", "Prolactin", "Estrogen", "Progesterone"],
    answer: "Oxytocin",
  },
  {
    id: 56,
    question: "Which hormone controls the release of eggs from the ovaries?",
    options: ["Luteinizing hormone (LH)", "Follicle-stimulating hormone (FSH)", "Prolactin", "Estrogen"],
    answer: "Luteinizing hormone (LH)",
  },
  {
    id: 57,
    question: "Which hormone stimulates sperm production in males?",
    options: ["Follicle-stimulating hormone (FSH)", "Luteinizing hormone (LH)", "Testosterone", "Estrogen"],
    answer: "Follicle-stimulating hormone (FSH)",
  },
  {
    id: 58,
    question: "Which gland secretes melatonin?",
    options: ["Pineal gland", "Pituitary gland", "Thyroid gland", "Adrenal gland"],
    answer: "Pineal gland",
  },
  {
    id: 59,
    question: "Which hormone increases heart rate and blood pressure during stress?",
    options: ["Adrenaline", "Cortisol", "Insulin", "Thyroxine"],
    answer: "Adrenaline",
  },
  {
    id: 60,
    question: "Which hormone regulates sodium and potassium levels in the blood?",
    options: ["Aldosterone", "ADH", "Thyroxine", "Growth hormone"],
    answer: "Aldosterone",
  },
  {
    id: 61,
    question: "Which hormone is secreted by the thyroid gland to regulate metabolism?",
    options: ["Thyroxine", "Calcitonin", "Parathyroid hormone", "Insulin"],
    answer: "Thyroxine",
  },
  {
    id: 62,
    question: "Which hormone increases blood glucose levels by promoting gluconeogenesis?",
    options: ["Glucagon", "Insulin", "Cortisol", "Adrenaline"],
    answer: "Glucagon",
  },
  {
    id: 63,
    question: "Which hormone regulates the body's sleep-wake cycle?",
    options: ["Melatonin", "Cortisol", "Adrenaline", "Growth hormone"],
    answer: "Melatonin",
  },
  {
    id: 64,
    question: "Which hormone is responsible for regulating water balance in the kidneys?",
    options: ["Antidiuretic hormone (ADH)", "Aldosterone", "Oxytocin", "Prolactin"],
    answer: "Antidiuretic hormone (ADH)",
  },
  {
    id: 65,
    question: "Which hormone stimulates the development of female secondary sexual characteristics?",
    options: ["Estrogen", "Testosterone", "Progesterone", "Oxytocin"],
    answer: "Estrogen",
  },
  {
    id: 66,
    question: "Which hormone prepares the uterus for pregnancy?",
    options: ["Progesterone", "Estrogen", "Oxytocin", "Testosterone"],
    answer: "Progesterone",
  },
  {
    id: 67,
    question: "Which hormone stimulates the anterior pituitary to release growth hormone?",
    options: ["Growth hormone-releasing hormone (GHRH)", "Somatostatin", "Thyrotropin-releasing hormone (TRH)", "Prolactin"],
    answer: "Growth hormone-releasing hormone (GHRH)",
  },
  {
    id: 68,
    question: "Which hormone inhibits growth hormone release?",
    options: ["Somatostatin", "Thyroxine", "Insulin", "Adrenaline"],
    answer: "Somatostatin",
  },
  {
    id: 69,
    question: "Which hormone is secreted by the thymus and plays a role in immune function?",
    options: ["Thymosin", "Insulin", "Adrenaline", "Cortisol"],
    answer: "Thymosin",
  },
  {
    id: 70,
    question: "Which hormone regulates electrolyte balance and blood pressure by acting on the kidneys?",
    options: ["Aldosterone", "ADH", "Cortisol", "Thyroxine"],
    answer: "Aldosterone",
  },
  {
    id: 71,
    question: "Which hormone controls milk production in the mammary glands?",
    options: ["Prolactin", "Oxytocin", "Estrogen", "Testosterone"],
    answer: "Prolactin",
  },
  {
    id: 72,
    question: "Which hormone stimulates the adrenal cortex to release cortisol?",
    options: ["Adrenocorticotropic hormone (ACTH)", "Growth hormone", "Thyroid-stimulating hormone (TSH)", "Prolactin"],
    answer: "Adrenocorticotropic hormone (ACTH)",
  },
  {
    id: 73,
    question: "Which hormone promotes sodium reabsorption in the kidneys?",
    options: ["Aldosterone", "ADH", "Cortisol", "Insulin"],
    answer: "Aldosterone",
  },
  {
    id: 74,
    question: "Which hormone regulates the menstrual cycle and maintains pregnancy?",
    options: ["Progesterone", "Estrogen", "Oxytocin", "Testosterone"],
    answer: "Progesterone",
  },
  {
    id: 75,
    question: "Which hormone regulates calcium and phosphate metabolism?",
    options: ["Parathyroid hormone (PTH)", "Calcitonin", "Insulin", "Cortisol"],
    answer: "Parathyroid hormone (PTH)",
  },
  {
    id: 76,
    question: "Which hormone increases blood calcium levels by stimulating bone resorption?",
    options: ["Parathyroid hormone (PTH)", "Calcitonin", "Insulin", "Glucagon"],
    answer: "Parathyroid hormone (PTH)",
  },
  {
    id: 77,
    question: "Which hormone is responsible for the fight-or-flight response?",
    options: ["Adrenaline", "Cortisol", "Insulin", "Thyroxine"],
    answer: "Adrenaline",
  },
  {
    id: 78,
    question: "Which hormone stimulates milk production in the mammary glands?",
    options: ["Prolactin", "Oxytocin", "Estrogen", "Progesterone"],
    answer: "Prolactin",
  },
  {
    id: 79,
    question: "Which gland secretes hormones that regulate calcium levels in the blood?",
    options: ["Parathyroid glands", "Thyroid gland", "Adrenal glands", "Pancreas"],
    answer: "Parathyroid glands",
  },
  {
    id: 80,
    question: "Which hormone reduces inflammation and suppresses the immune response?",
    options: ["Cortisol", "Adrenaline", "Insulin", "Growth hormone"],
    answer: "Cortisol",
  },
  {
    id: 81,
    question: "Which hormone controls the basal metabolic rate?",
    options: ["Thyroxine (T4)", "Growth hormone", "Cortisol", "Adrenaline"],
    answer: "Thyroxine (T4)",
  },
  {
    id: 82,
    question: "Which hormone helps regulate blood pressure by controlling water balance?",
    options: ["Antidiuretic hormone (ADH)", "Aldosterone", "Insulin", "Oxytocin"],
    answer: "Antidiuretic hormone (ADH)",
  },
  {
    id: 83,
    question: "Which hormone triggers uterine contractions during labor?",
    options: ["Oxytocin", "Prolactin", "Estrogen", "Progesterone"],
    answer: "Oxytocin",
  },
  {
    id: 84,
    question: "Which hormone promotes the development of male secondary sexual characteristics?",
    options: ["Testosterone", "Estrogen", "Progesterone", "Growth hormone"],
    answer: "Testosterone",
  },
  {
    id: 85,
    question: "Which hormone stimulates the adrenal cortex to produce glucocorticoids?",
    options: ["Adrenocorticotropic hormone (ACTH)", "Thyroid-stimulating hormone (TSH)", "Growth hormone", "Prolactin"],
    answer: "Adrenocorticotropic hormone (ACTH)",
  },
  {
    id: 86,
    question: "Which hormone is secreted by the pineal gland?",
    options: ["Melatonin", "Insulin", "Cortisol", "Adrenaline"],
    answer: "Melatonin",
  },
  {
    id: 87,
    question: "Which hormone regulates sodium reabsorption in the kidneys to control blood pressure?",
    options: ["Aldosterone", "Antidiuretic hormone (ADH)", "Insulin", "Thyroxine"],
    answer: "Aldosterone",
  },
  {
    id: 88,
    question: "Which hormone stimulates gluconeogenesis and increases blood glucose during stress?",
    options: ["Cortisol", "Insulin", "Glucagon", "Adrenaline"],
    answer: "Cortisol",
  },
  {
    id: 89,
    question: "Which hormone controls the secretion of thyroid hormones?",
    options: ["Thyroid-stimulating hormone (TSH)", "Adrenocorticotropic hormone (ACTH)", "Growth hormone", "Prolactin"],
    answer: "Thyroid-stimulating hormone (TSH)",
  },
  {
    id: 90,
    question: "Which hormone decreases blood calcium levels?",
    options: ["Calcitonin", "Parathyroid hormone", "Insulin", "Glucagon"],
    answer: "Calcitonin",
  },
  {
    id: 91,
    question: "Which hormone stimulates the testes to produce testosterone?",
    options: ["Luteinizing hormone (LH)", "Follicle-stimulating hormone (FSH)", "Prolactin", "Growth hormone"],
    answer: "Luteinizing hormone (LH)",
  },
  {
    id: 92,
    question: "Which hormone is involved in the body's stress response and increases blood glucose?",
    options: ["Cortisol", "Insulin", "Adrenaline", "Thyroxine"],
    answer: "Cortisol",
  },
  {
    id: 93,
    question: "Which hormone promotes milk let-down in breastfeeding?",
    options: ["Oxytocin", "Prolactin", "Estrogen", "Progesterone"],
    answer: "Oxytocin",
  },
  {
    id: 94,
    question: "Which hormone is produced by the pancreas to lower blood sugar?",
    options: ["Insulin", "Glucagon", "Somatostatin", "Pancreatic polypeptide"],
    answer: "Insulin",
  },
  {
    id: 95,
    question: "Which hormone is responsible for stimulating egg development in the ovaries?",
    options: ["Follicle-stimulating hormone (FSH)", "Luteinizing hormone (LH)", "Estrogen", "Progesterone"],
    answer: "Follicle-stimulating hormone (FSH)",
  },
  {
    id: 96,
    question: "Which hormone regulates the menstrual cycle and maintains pregnancy?",
    options: ["Progesterone", "Estrogen", "Oxytocin", "Testosterone"],
    answer: "Progesterone",
  },
  {
    id: 97,
    question: "Which hormone controls the release of glucose from the liver into the blood?",
    options: ["Glucagon", "Insulin", "Cortisol", "Adrenaline"],
    answer: "Glucagon",
  },
  {
    id: 98,
    question: "Which hormone acts on the kidneys to conserve water?",
    options: ["Antidiuretic hormone (ADH)", "Aldosterone", "Oxytocin", "Prolactin"],
    answer: "Antidiuretic hormone (ADH)",
  },
  {
    id: 99,
    question: "Which hormone stimulates the secretion of digestive enzymes from the pancreas?",
    options: ["Secretin", "Gastrin", "Cholecystokinin (CCK)", "Glucagon"],
    answer: "Cholecystokinin (CCK)",
  },
  {
    id: 100,
    question: "Which hormone is responsible for increasing heart rate and blood flow during stress?",
    options: ["Adrenaline", "Cortisol", "Insulin", "Thyroxine"],
    answer: "Adrenaline",
  }
];