let timeLeft = 7200; // 2 hours in seconds
const questions = [
    {
    id: 1,
    question: "What is the primary function of the respiratory system?",
    options: ["Digest food", "Exchange gases", "Pump blood", "Filter waste"],
    answer: "Exchange gases",
  },
  {
    id: 2,
    question: "Which structure prevents food from entering the trachea during swallowing?",
    options: ["Epiglottis", "Larynx", "Pharynx", "Bronchi"],
    answer: "Epiglottis",
  },
  {
    id: 3,
    question: "Where does gas exchange occur in the lungs?",
    options: ["Bronchi", "Alveoli", "Trachea", "Larynx"],
    answer: "Alveoli",
  },
  {
    id: 4,
    question: "Which muscle is primarily responsible for breathing?",
    options: ["Diaphragm", "Heart", "Larynx", "Esophagus"],
    answer: "Diaphragm",
  },
  {
    id: 5,
    question: "What is the windpipe called?",
    options: ["Bronchi", "Trachea", "Pharynx", "Larynx"],
    answer: "Trachea",
  },
  {
    id: 6,
    question: "Which part of the respiratory system is known as the voice box?",
    options: ["Larynx", "Pharynx", "Trachea", "Bronchi"],
    answer: "Larynx",
  },
  {
    id: 7,
    question: "What are the tiny hair-like structures that filter inhaled air called?",
    options: ["Cilia", "Villi", "Flagella", "Microvilli"],
    answer: "Cilia",
  },
  {
    id: 8,
    question: "Which gas is primarily inhaled during respiration?",
    options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    answer: "Oxygen",
  },
  {
    id: 9,
    question: "Which gas is primarily exhaled during respiration?",
    options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    answer: "Carbon dioxide",
  },
  {
    id: 10,
    question: "How many lobes does the right lung have?",
    options: ["2", "3", "4", "5"],
    answer: "3",
  },
  {
    id: 11,
    question: "Which membrane surrounds the lungs?",
    options: ["Peritoneum", "Pleura", "Pericardium", "Meninges"],
    answer: "Pleura",
  },
  {
    id: 12,
    question: "What is the name of the tiny air sacs in the lungs where gas exchange occurs?",
    options: ["Alveoli", "Bronchioles", "Trachea", "Capillaries"],
    answer: "Alveoli",
  },
  {
    id: 13,
    question: "What is tidal volume?",
    options: ["Maximum air inhaled", "Air inhaled or exhaled during normal breathing", "Air left after exhalation", "Air forcibly exhaled"],
    answer: "Air inhaled or exhaled during normal breathing",
  },
  {
    id: 14,
    question: "Which nerve controls the diaphragm?",
    options: ["Vagus nerve", "Phrenic nerve", "Sciatic nerve", "Median nerve"],
    answer: "Phrenic nerve",
  },
  {
    id: 15,
    question: "What part of the brain controls the rate of breathing?",
    options: ["Cerebellum", "Medulla oblongata", "Hypothalamus", "Cerebrum"],
    answer: "Medulla oblongata",
  },
  {
    id: 16,
    question: "What prevents the collapse of the trachea?",
    options: ["Cartilage rings", "Muscle fibers", "Bone", "Ligaments"],
    answer: "Cartilage rings",
  },
  {
    id: 17,
    question: "Which process involves oxygen moving from alveoli to blood?",
    options: ["Internal respiration", "External respiration", "Cellular respiration", "Pulmonary ventilation"],
    answer: "External respiration",
  },
  {
    id: 18,
    question: "Which blood component carries oxygen?",
    options: ["Plasma", "Red blood cells", "White blood cells", "Platelets"],
    answer: "Red blood cells",
  },
  {
    id: 19,
    question: "What is the term for inflammation of the lungs?",
    options: ["Bronchitis", "Pneumonia", "Asthma", "Emphysema"],
    answer: "Pneumonia",
  },
  {
    id: 20,
    question: "Which structure connects the throat to the lungs?",
    options: ["Bronchi", "Trachea", "Larynx", "Pharynx"],
    answer: "Trachea",
  },
  {
    id: 21,
    question: "What is the name of the tiny tubes that branch from the bronchi?",
    options: ["Bronchioles", "Alveoli", "Capillaries", "Lobules"],
    answer: "Bronchioles",
  },
  {
    id: 22,
    question: "Which condition is characterized by narrowing of airways and difficulty breathing?",
    options: ["Asthma", "Pneumonia", "Tuberculosis", "Emphysema"],
    answer: "Asthma",
  },
  {
    id: 23,
    question: "What is the function of surfactant in the lungs?",
    options: ["Increase oxygen absorption", "Reduce surface tension in alveoli", "Filter dust particles", "Transport carbon dioxide"],
    answer: "Reduce surface tension in alveoli",
  },
  {
    id: 24,
    question: "Which respiratory disorder is caused by destruction of alveoli walls?",
    options: ["Asthma", "Emphysema", "Bronchitis", "Pneumonia"],
    answer: "Emphysema",
  },
  {
    id: 25,
    question: "What is the normal respiratory rate for adults (breaths per minute)?",
    options: ["6-8", "12-20", "24-30", "30-40"],
    answer: "12-20",
  },
  {
    id: 26,
    question: "What is the role of the nasal cavity in respiration?",
    options: ["Produce mucus", "Filter, warm, and moisten air", "Exchange gases", "Control airflow"],
    answer: "Filter, warm, and moisten air",
  },
  {
    id: 27,
    question: "Which structure acts as a passageway for both air and food?",
    options: ["Pharynx", "Larynx", "Trachea", "Esophagus"],
    answer: "Pharynx",
  },
  {
    id: 28,
    question: "Which gas law explains the mechanics of breathing?",
    options: ["Boyle's law", "Charles's law", "Dalton's law", "Henry's law"],
    answer: "Boyle's law",
  },
  {
    id: 29,
    question: "What type of epithelium lines most of the respiratory tract?",
    options: ["Simple squamous", "Pseudostratified ciliated columnar", "Transitional", "Stratified squamous"],
    answer: "Pseudostratified ciliated columnar",
  },
  {
    id: 30,
    question: "What is the function of the cilia in the respiratory tract?",
    options: ["Secrete mucus", "Trap dust particles", "Move mucus upward", "Absorb oxygen"],
    answer: "Move mucus upward",
  },
  {
    id: 31,
    question: "Which part of the brain detects changes in blood CO2 and O2 levels to regulate breathing?",
    options: ["Medulla oblongata", "Cerebellum", "Hypothalamus", "Cerebrum"],
    answer: "Medulla oblongata",
  },
  {
    id: 32,
    question: "What is the volume of air remaining in lungs after forced expiration called?",
    options: ["Tidal volume", "Residual volume", "Inspiratory reserve volume", "Expiratory reserve volume"],
    answer: "Residual volume",
  },
  {
    id: 33,
    question: "What is the total lung capacity?",
    options: ["Maximum volume of air lungs can hold", "Air inhaled during normal breathing", "Air left after exhalation", "Air forcibly exhaled"],
    answer: "Maximum volume of air lungs can hold",
  },
  {
    id: 34,
    question: "Which gas has the highest concentration in atmospheric air?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"],
    answer: "Nitrogen",
  },
  {
    id: 35,
    question: "What is hyperventilation?",
    options: ["Rapid and deep breathing", "Slow and shallow breathing", "Normal breathing", "Absence of breathing"],
    answer: "Rapid and deep breathing",
  },
  {
    id: 36,
    question: "Which structure divides the nasal cavity into two halves?",
    options: ["Nasal septum", "Turbinates", "Pharynx", "Larynx"],
    answer: "Nasal septum",
  },
  {
    id: 37,
    question: "Which respiratory disorder is caused by Mycobacterium tuberculosis?",
    options: ["Pneumonia", "Tuberculosis", "Bronchitis", "Emphysema"],
    answer: "Tuberculosis",
  },
  {
    id: 38,
    question: "What is the function of the sinuses in the respiratory system?",
    options: ["Produce sound", "Reduce weight of skull and produce mucus", "Filter air", "Absorb oxygen"],
    answer: "Reduce weight of skull and produce mucus",
  },
  {
    id: 39,
    question: "Which condition involves inflammation of the bronchial tubes?",
    options: ["Asthma", "Bronchitis", "Pneumonia", "Emphysema"],
    answer: "Bronchitis",
  },
  {
    id: 40,
    question: "Which respiratory pigment carries oxygen in the blood?",
    options: ["Hemoglobin", "Myoglobin", "Chlorophyll", "Carotene"],
    answer: "Hemoglobin",
  },
  {
    id: 41,
    question: "What is apnea?",
    options: ["Absence of breathing", "Rapid breathing", "Slow breathing", "Difficulty breathing"],
    answer: "Absence of breathing",
  },
  {
    id: 42,
    question: "Which structure is known as the Adam’s apple?",
    options: ["Thyroid cartilage", "Cricoid cartilage", "Arytenoid cartilage", "Epiglottis"],
    answer: "Thyroid cartilage",
  },
  {
    id: 43,
    question: "What is the role of the soft palate in respiration?",
    options: ["Prevent food from entering nasal cavity", "Control airflow", "Filter air", "Produce mucus"],
    answer: "Prevent food from entering nasal cavity",
  },
  {
    id: 44,
    question: "Which lung is smaller to accommodate the heart?",
    options: ["Right lung", "Left lung", "Both are equal", "None of these"],
    answer: "Left lung",
  },
  {
    id: 45,
    question: "What is chemoreceptor sensitivity primarily responsive to?",
    options: ["Oxygen levels", "Carbon dioxide levels", "pH levels", "Nitrogen levels"],
    answer: "Carbon dioxide levels",
  },
  {
    id: 46,
    question: "Which of the following is a chronic obstructive pulmonary disease (COPD)?",
    options: ["Asthma", "Emphysema", "Pneumonia", "Tuberculosis"],
    answer: "Emphysema",
  },
  {
    id: 47,
    question: "What is the function of the cartilaginous rings in the trachea?",
    options: ["Allow flexibility and prevent collapse", "Produce mucus", "Filter air", "Absorb oxygen"],
    answer: "Allow flexibility and prevent collapse",
  },
  {
    id: 48,
    question: "Which structure is the site for speech production?",
    options: ["Larynx", "Pharynx", "Trachea", "Bronchi"],
    answer: "Larynx",
  },
  {
    id: 49,
    question: "What is the main function of the respiratory mucosa?",
    options: ["Secrete mucus and trap particles", "Exchange gases", "Control airflow", "Produce surfactant"],
    answer: "Secrete mucus and trap particles",
  },
  {
    id: 50,
    question: "What is the term for inflammation of the pleura?",
    options: ["Pleuritis", "Pneumonia", "Bronchitis", "Asthma"],
    answer: "Pleuritis",
  },
  {
    id: 51,
    question: "Which type of cells in the alveoli produce surfactant?",
    options: ["Type I pneumocytes", "Type II pneumocytes", "Macrophages", "Goblet cells"],
    answer: "Type II pneumocytes",
  },
  {
    id: 52,
    question: "What is the role of alveolar macrophages?",
    options: ["Produce surfactant", "Engulf pathogens and debris", "Absorb oxygen", "Produce mucus"],
    answer: "Engulf pathogens and debris",
  },
  {
    id: 53,
    question: "What is the respiratory membrane?",
    options: ["Membrane surrounding the lungs", "Barrier between alveoli and blood capillaries", "Membrane lining the trachea", "Membrane in the nasal cavity"],
    answer: "Barrier between alveoli and blood capillaries",
  },
  {
    id: 54,
    question: "Which condition is characterized by excessive mucus production and airway inflammation?",
    options: ["Chronic bronchitis", "Asthma", "Emphysema", "Pneumonia"],
    answer: "Chronic bronchitis",
  },
  {
    id: 55,
    question: "Which part of the respiratory system is involved in warming inspired air?",
    options: ["Nasal cavity", "Trachea", "Bronchi", "Alveoli"],
    answer: "Nasal cavity",
  },
  {
    id: 56,
    question: "Which artery carries deoxygenated blood to the lungs?",
    options: ["Pulmonary artery", "Pulmonary vein", "Aorta", "Coronary artery"],
    answer: "Pulmonary artery",
  },
  {
    id: 57,
    question: "What is the function of the pleural fluid?",
    options: ["Lubricate pleural surfaces", "Aid gas exchange", "Carry oxygen", "Produce surfactant"],
    answer: "Lubricate pleural surfaces",
  },
  {
    id: 58,
    question: "What is the term for the volume of air forcibly exhaled after a normal exhalation?",
    options: ["Tidal volume", "Expiratory reserve volume", "Inspiratory reserve volume", "Residual volume"],
    answer: "Expiratory reserve volume",
  },
  {
    id: 59,
    question: "Which respiratory structure is lined with stratified squamous epithelium to withstand abrasion?",
    options: ["Trachea", "Nasal cavity", "Oropharynx", "Alveoli"],
    answer: "Oropharynx",
  },
  {
    id: 60,
    question: "What is the term for inflammation of the larynx?",
    options: ["Laryngitis", "Pharyngitis", "Bronchitis", "Pneumonia"],
    answer: "Laryngitis",
  },
  {
    id: 61,
    question: "What part of the brainstem contains the respiratory rhythmicity centers?",
    options: ["Medulla oblongata", "Pons", "Midbrain", "Cerebellum"],
    answer: "Medulla oblongata",
  },
  {
    id: 62,
    question: "Which cells produce mucus in the respiratory tract?",
    options: ["Goblet cells", "Ciliated epithelial cells", "Alveolar macrophages", "Type I pneumocytes"],
    answer: "Goblet cells",
  },
  {
    id: 63,
    question: "What is external respiration?",
    options: ["Gas exchange between blood and tissues", "Gas exchange between alveoli and blood", "Cellular respiration", "Breathing process"],
    answer: "Gas exchange between alveoli and blood",
  },
  {
    id: 64,
    question: "Which lung disease is characterized by destruction of alveolar walls and loss of lung elasticity?",
    options: ["Emphysema", "Asthma", "Pneumonia", "Bronchitis"],
    answer: "Emphysema",
  },
  {
    id: 65,
    question: "Which part of the respiratory system conducts air to the alveoli?",
    options: ["Bronchioles", "Trachea", "Pharynx", "Larynx"],
    answer: "Bronchioles",
  },
  {
    id: 66,
    question: "Which gas law explains the partial pressure of gases in mixtures?",
    options: ["Dalton’s law", "Boyle’s law", "Henry’s law", "Charles’s law"],
    answer: "Dalton’s law",
  },
  {
    id: 67,
    question: "What is the name of the reflex that protects the respiratory tract from foreign particles?",
    options: ["Cough reflex", "Sneezing", "Gag reflex", "Blink reflex"],
    answer: "Cough reflex",
  },
  {
    id: 68,
    question: "Which disease is caused by inflammation and infection of the alveoli?",
    options: ["Pneumonia", "Bronchitis", "Asthma", "Emphysema"],
    answer: "Pneumonia",
  },
  {
    id: 69,
    question: "Which structure prevents food from entering the nasal cavity during swallowing?",
    options: ["Soft palate", "Epiglottis", "Hard palate", "Uvula"],
    answer: "Soft palate",
  },
  {
    id: 70,
    question: "What is the function of the nasal conchae?",
    options: ["Increase surface area to warm and moisten air", "Filter air", "Produce mucus", "Absorb oxygen"],
    answer: "Increase surface area to warm and moisten air",
  },
  {
    id: 71,
    question: "Which condition involves blockage of airflow due to bronchial constriction?",
    options: ["Asthma", "Pneumonia", "Bronchitis", "Emphysema"],
    answer: "Asthma",
  },
  {
    id: 72,
    question: "What is the role of carbonic anhydrase in red blood cells?",
    options: ["Convert CO2 to bicarbonate for transport", "Carry oxygen", "Produce energy", "Filter blood"],
    answer: "Convert CO2 to bicarbonate for transport",
  },
  {
    id: 73,
    question: "What is the function of the surfactant produced in the lungs?",
    options: ["Reduce surface tension in alveoli", "Trap dust", "Aid in mucus production", "Transport oxygen"],
    answer: "Reduce surface tension in alveoli",
  },
  {
    id: 74,
    question: "Which muscle assists the diaphragm during forced inspiration?",
    options: ["Intercostal muscles", "Abdominal muscles", "Pectoral muscles", "Trapezius muscles"],
    answer: "Intercostal muscles",
  },
  {
    id: 75,
    question: "What is hemoglobin saturation?",
    options: ["Percentage of hemoglobin bound to oxygen", "Amount of hemoglobin in blood", "Rate of oxygen diffusion", "Volume of oxygen in lungs"],
    answer: "Percentage of hemoglobin bound to oxygen",
  },
  {
    id: 76,
    question: "Which structure closes off the trachea during swallowing to prevent food from entering?",
    options: ["Epiglottis", "Uvula", "Larynx", "Pharynx"],
    answer: "Epiglottis",
  },
  {
    id: 77,
    question: "What is the primary muscle responsible for normal, quiet breathing?",
    options: ["Diaphragm", "Intercostal muscles", "Abdominal muscles", "Pectoral muscles"],
    answer: "Diaphragm",
  },
  {
    id: 78,
    question: "Which part of the brain regulates voluntary control of breathing?",
    options: ["Cerebral cortex", "Medulla oblongata", "Pons", "Hypothalamus"],
    answer: "Cerebral cortex",
  },
  {
    id: 79,
    question: "Which of the following increases oxygen release from hemoglobin in tissues?",
    options: ["Low pH", "High pH", "Low CO2", "Low temperature"],
    answer: "Low pH",
  },
  {
    id: 80,
    question: "Which gas primarily drives the respiratory drive under normal conditions?",
    options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
    answer: "Carbon dioxide",
  },
  {
    id: 81,
    question: "What is the name of the air sacs where gas exchange occurs?",
    options: ["Alveoli", "Bronchioles", "Trachea", "Bronchi"],
    answer: "Alveoli",
  },
  {
    id: 82,
    question: "What is the condition called when air leaks into the space between the lung and chest wall?",
    options: ["Pneumothorax", "Hemothorax", "Pleural effusion", "Bronchitis"],
    answer: "Pneumothorax",
  },
  {
    id: 83,
    question: "Which part of the respiratory system is also known as the voice box?",
    options: ["Larynx", "Pharynx", "Trachea", "Bronchi"],
    answer: "Larynx",
  },
  {
    id: 84,
    question: "Which lung volume is the amount of air inhaled or exhaled during normal breathing?",
    options: ["Tidal volume", "Inspiratory reserve volume", "Residual volume", "Expiratory reserve volume"],
    answer: "Tidal volume",
  },
  {
    id: 85,
    question: "What is the function of the nasal hairs?",
    options: ["Filter large particles", "Warm air", "Moisten air", "Produce mucus"],
    answer: "Filter large particles",
  },
  {
    id: 86,
    question: "Which respiratory condition is characterized by the collapse of alveoli?",
    options: ["Atelectasis", "Pneumonia", "Asthma", "Emphysema"],
    answer: "Atelectasis",
  },
  {
    id: 87,
    question: "What is the major function of the diaphragm during inspiration?",
    options: ["Increase thoracic cavity volume", "Decrease lung volume", "Close airways", "Produce mucus"],
    answer: "Increase thoracic cavity volume",
  },
  {
    id: 88,
    question: "Which respiratory structure contains the vocal cords?",
    options: ["Larynx", "Pharynx", "Trachea", "Bronchi"],
    answer: "Larynx",
  },
  {
    id: 89,
    question: "What is the term for breathing that occurs only when necessary, such as during exercise?",
    options: ["Forced breathing", "Quiet breathing", "Apnea", "Dyspnea"],
    answer: "Forced breathing",
  },
  {
    id: 90,
    question: "Which cells form the blood-air barrier in the lungs?",
    options: ["Type I pneumocytes", "Type II pneumocytes", "Alveolar macrophages", "Goblet cells"],
    answer: "Type I pneumocytes",
  },
  {
    id: 91,
    question: "What is the main function of the pharynx in the respiratory system?",
    options: ["Passageway for air and food", "Produce mucus", "Gas exchange", "Voice production"],
    answer: "Passageway for air and food",
  },
  {
    id: 92,
    question: "Which term describes difficulty breathing or shortness of breath?",
    options: ["Dyspnea", "Apnea", "Tachypnea", "Bradypnea"],
    answer: "Dyspnea",
  },
  {
    id: 93,
    question: "What is the function of the bronchi in the respiratory system?",
    options: ["Conduct air to lungs", "Gas exchange", "Produce mucus", "Warm air"],
    answer: "Conduct air to lungs",
  },
  {
    id: 94,
    question: "What is the term for inflammation of the bronchial tubes?",
    options: ["Bronchitis", "Pneumonia", "Asthma", "Emphysema"],
    answer: "Bronchitis",
  },
  {
    id: 95,
    question: "Which respiratory disease is characterized by hypersensitivity causing airway constriction?",
    options: ["Asthma", "Emphysema", "Bronchitis", "Pneumonia"],
    answer: "Asthma",
  },
  {
    id: 96,
    question: "Which structure connects the larynx to the bronchi?",
    options: ["Trachea", "Pharynx", "Alveoli", "Esophagus"],
    answer: "Trachea",
  },
  {
    id: 97,
    question: "Which lung lobe is the largest?",
    options: ["Right lower lobe", "Left upper lobe", "Right middle lobe", "Left lower lobe"],
    answer: "Right lower lobe",
  },
  {
    id: 98,
    question: "What does spirometry measure?",
    options: ["Lung volumes and capacities", "Blood oxygen levels", "Heart rate", "Blood pressure"],
    answer: "Lung volumes and capacities",
  },
  {
    id: 99,
    question: "Which molecule in blood transports carbon dioxide?",
    options: ["Bicarbonate ion", "Hemoglobin", "Myoglobin", "Oxygen"],
    answer: "Bicarbonate ion",
  },
  {
    id: 100,
    question: "What is the term for increased respiratory rate?",
    options: ["Tachypnea", "Bradypnea", "Apnea", "Dyspnea"],
    answer: "Tachypnea",
  }
];